### ISSUE TITLE
Unable to push log

### ISSUE THREAD

**Issue by MangMax** [konradkaminski/serilog-sinks-openobserve-kkp#11]
Hi, thank you so much for making this library！I tried to push the logs to my own deployed openobserve, but it didn't work, is there something I need to be aware of?

**Comment by konradkaminski** [comment]
hi @MangMax 

I've verified it and works as expected. 

But there are some things to verify:

1. organization name is: default, this organization should be created by default;
2. is stream for logs created? by default lib is sending all logs to stream named: default, you can change it in configuration;
3. in some cases restart of openobserve is required (especially after creating first stream);

**Comment by MangMax** [comment]
Thanks, it's working!
